os: linux
sudo: required

env:
  - export CC="gcc-4.8"

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - gcc-4.8

before_install:
  - sudo apt-get -y -qq update
  - sudo apt-get -y -qq install build-essential libxslt-dev zlib1g-dev aria2

install:
  - ./build.sh

script:
  - ./nginx -v
